year = 2020
month = 6
date = 9
goto = 8

story = """
The [green()]school year is almost over[normal()]. Only two more weeks to go. You’ve [green()]gotten used to remote learning[normal()] and have gotten [green()]better at managing your time[normal()]. 

# green()
You appreciate how you are able to learn from the comfort of your own home. 
# pause()

However, you still remember how all your 8th grade activities were cancelled, including your family’s vacation to DisneyLand.
# normal() 
# pause()

Some of your teachers stopped doing zoom meetings and just give lessons to do by yourself. It’s definitely not the same experience as being in regular school. 
# pause()

# day0070

"""