year = 2021
month = 2
date = 29# (comes after feb news string)
goto = 123

story = """
February 29th, 2021: 
It was really exciting for you to hear about the [green()]Mars rover and orbit missions[normal()] that had happened this month. 
# pause()

# green
It is great news for you and many others that your region is now in Phase 2 of Covid reopening. 
# pause()

You are now able to order food for more small businesses, as they are starting to open back up. 
# normal()

You and your mom decide to go buy some food from local resturaunts and bakeries.
# pause()
# day0200
"""
