year = 2020
month = 9
date = 9
goto = 13

story = """
# green()
Today is the first day of your freshman year! 
# normal()
Classes aren’t that different from middle school, but you are worried about the homework workload. You have no zoom problems. 
# pause()
You look at all the profiles on the zoom meeting. You remember that there are people from 4 schools mixed together. You don’t see any of your close friends in your class. Only 2-3 familiar faces. The rest of your new classmates you haven’t met yet. 
# pause()
# green()
You remember how awkward zoom meetings are. Especially going into breakout rooms. Most people had their cameras off, and a lot of people didn’t talk at all. 
# normal()
Some classes were kind of confusing too. You had to get used to the strange class schedules. You couldn’t believe that you had 20 minutes of passing time between classes.
# pause()
# green()
It’s your first day, but you already have homework. You add all your tasks to your to-do list.
# normal()
That day, you also decided to download another app that tells you the news, so you can keep up with the daily events. 
# pause()
# day12()
"""