year = 2020
month = 12
date = 14#-18

story = """
The final exams are here! You are supposed to only attend 3 classes a day. Each being 1 hour long. When you receive your test scores, you breathe a sigh of relief. You did pretty well! There were some answers that you missed that made you angry with yourself. Thatâ€™s because on those ones, you self doubted yourself and changed your answer. However, you now get a 2 and a half weeks break from school, woo-hoo!"""
