year = 2021
month = 1
date = 13#-20 (comes before jan news)
goto = 19

story = """

[green()]It was hard to comprehend everything that was happening this month.[normal()]
# pause()

On top of that, your [green()]class schedule has changed due to school learning regulations.[normal()] 
# normal()

This [green()]new schedule is kind of wonky[normal()], and you’re having a [green()]hard time getting used to it[normal()]. Also, you have a [green()]lot of homework[normal()], and you’re worried that you won’t get it done in time.
# pause()

x eng() math() sci()

"""
[[notification]]
title = "News Notification"
text = "Jan. 13th. The US House of Representatives officially impeached President Donald Trump for “incitement of insurrection.” Votings were 232-197. This is the first time in history a US President is impeached twice."
date = "January 13th, 2021"

[[notification]]
title = "News Notification"
text = "The inauguration of the 46th President of the U.S, Joe Biden and  49th Vice President, Kamala Harris happened."
date = "January 20th, 2021"

