year = 2020
month = 3
date = 13

story = """
You hear the staticky sound of the school speakers turning on. Everyone sitting on the edge of their seat, waiting. Anticipating.

Immediately, the principal says:  “Due to the current conditions, we will unfortunately be resuming classes remotely...” 

These were the words said on March 13th of 2020, school year of 2020-2021. Times of foreshadowing twirl in your mind right then and there.  One by one, classmates had stopped showing up to school, any physical contact had been forbidden, and there was the intense sanitization of desks, tables, and chairs. 

The sound of the announcements start to tune out. You felt like the world stopped right in its tracks. You realize that any school activities would be canceled. All sports, games, clubs, and field trips.

Learning from home? You had found that pretty exciting and assured yourself that this wouldn’t last very long.
"""

[[notification]]
title = "Test notification..."