year = 2020
month = 5
date = 12
goto = 5

story = """

You also [green()]aren’t getting enough time outside of your room and haven’t been able to socialize with others much[normal()]. 

       `'::.
    _________H ,%%&%,
   /\     _   \%&&%%&%
  /  \___/^\___\%&%%&&
  |  | []   [] |%\Y&%'
  |  |   .-.   | ||  
~~@._|@@_|||_@@|~||~~~~~~~~~~~~~
     `""") )"""`
		 
#normal()
# pause()

# day4a()
"""

#"""
[[notification]]
title = "Text Notification"
text = "Ventilators and testing kit shortage in hospitals."
date = "May 12th ,2020"


