year = 2020
month = 5
date = 30
goto = 7


story = """

You and your [green()]parents[normal()] have been [green()]worrying about[normal()] your [green()]grandparents[normal()] lately. Your aunt, cousins, and grandparents live in the same house. That is why your aunt and cousins can’t leave, due to the [green()]risk of exposing the virus to[normal()] your [green()]grandparents. 
  ____||____
 ///////////\\
///////////  \\
|    _    |  |
|[] | | []|[]|
|   | |   |  |
# normal()
# pause()

Right then,you feel a [green()]wave of sadness[normal()] pass through your body. You realized that you haven’t been able to see your cousins in 3 months and you miss spending time with them. Because they are younger than you, you guys often bicker, but it was all fun in games most of the time. 
# pause()

# green()
You suggest to your parents that you could drop off supplies in front of your grandparents’ house along with some meals.
# pause()

Your parents agree, and you are delighted.
,-' `-._,-' `-._,-' `-._,-' `-._,-' `-._,-' `-._,-' 
# normal()
# day6a()
"""

[[notification]]
title = "Text Notification"
text = "Hospitals are running out of space and hospital beds and are now using non-hospital buildings, like stadiums, to house patients. ."
date = "May 30th, 2020"
