year = 2020
month = 6
date = 9
goto = 8

story = """

Instead of being stuck in your house all day doing homework, you occasionally go outside to your backyard for some fresh air. 

After finishing your homework, you decide to [green()]spend time with your little sister. 
# normal()
# pause()

          _( }
   -=  _  <<  \
      `.\__/`/\\
 -=     '--'\\  `
      -=    //
            \)

Playing with little sister:
# pause()
# day7a()
# pause()

# green()
This was really fun for you. You realize that you should play more with your sister. 

This has made you really happy. You found a way to cope with the stress youâ€™ve had with school.
# normal()
"""
