year = 2020
month = 7
date = 4
goto = 10

story = '''
Today is the [green()]4th of July[normal()]!

                                   .''.       
       .''.      .        *''*    :_\/_:     . 
      :_\/_:   _\(/_  .:.*_\/_*   : /\ :  .'.:.'.
  .''.: /\ :   ./)\   ':'* /\ * :  '..'.  -=:o:=-
 :_\/_:'.:::.    ' *''*    * '.\'/.' _\(/_'.':'.'
 : /\ : :::::     *_\/_*     -= o =-  /)\    '  *
  '..'  ':::'     * /\ *     .'/.\'.   '
      *            *..*         :
        *
        *
# pause ()

Usually, your parents would invite over family for a BBQ party. 
# pause()

You notice that your [green()]parents were also sad about not being able to see family too.[normal()]Most people [green()]canceled doing fireworks this year[normal()], too. 
# pause()

You suddenly have an idea!
     _____  
   .'     `.
  /         \\
 |           | 
 '.  +^^^+  .'
   `. \./ .'
     |_|_|  
     (___)    
     (___)
     `---'
# pause()
You decide to call some friends and family to wish them a happy 4th of July.
# day9b()
'''