year = 2020
month = 11
date = 26
goto = 15



story = '''
# green()
 It's Thanksgiving!

              _______       _\"_
          _ /     |   \_   (  .)
        _/   \     |     \ /   >
      / \      \    |     /   }
    /      \     _ - -   /   }}
   | -  _    \-/            )}
  / _ _ _ _> \             /
  |__________ \   / /  / /
               \_/_/___/
                 |   |
                 |   |
                 |   |
                /!\ /!\\
	
 # normal()

It’s been a hard year for everyone, so you and your family decide to do something to give thanks. 
# pause()

You choose to donate a few boxes of canned food to the food bank,and cook some Thanksgiving meals to drop off at your grandparents’ house. 
# pause()

Time for [green()]Thanksgiving dinner![normal()]
# pause()

# day14a()
# pause()

You are also glad that you got a 5 day weekend. You are relieved that you get a break from school, since it has been pretty stressful and tiring.
'''
