year = 2020
month = 3
date = 14

story = """
8:15 AM: Your alarm clock rings. It’s 8:15 a.m. Today is the first day of quarantine. You get out of bed, brush your teeth, and have some breakfast. Bacon and eggs. The usual. You contemplate whether or not to make your bed and change out of your pajamas. Meh, it’s fine, you think. 
You sit at your desk and open up Zoom on your computer. You only have 7 minutes before class starts. You sign into zoom and enter your zoom code. After being accepted into the waiting room, you see a black screen that says “connecting” in white letters. Wait, something went wrong. You got kicked out of the meeting! You ask yourself: Why? What’s wrong? . You try to rejoin again and again, but the same thing keeps happening. 
WHAT WILL YOU DO? Try to go to a different part of the house to see if the connection is better there, email your teacher about what's going on. 

Zoom finally worked! You got into your first class, pre-Algebra. You breathe a sigh of relief. Your heart was still racing rapidly and you have a bit of a headache from the stress of all that. However, after that first Zoom meeting, you kind of get the jist of things, and joining the rest of your Zoom meetings is easier. Nothing more to worry about for the rest of the day. Teachers were just going over work and explaining how Zoom classes would work. First day, complete. Phew!
"""




