year = 2020
month = 7
date = 4
goto = 10

story = """
Today is the [green()]4th of July[normal()]!
# pause()

That evening, your parents tell you that they planned some fun activities for you and your sister to do this July 4th. 

# green()
You and your parents are going to try to bake something for after dinner dessert. Happy that you wouldnâ€™t spend your 4th of July gloomily, you instantly agree. 
# normal()
# pause()
# day9()
"""